package clinic;

/**
 * Base class representing an animal.
 * @since 1.0
 */
public class Animal implements Pet
{
    // name of the pet
    private String name;
    
    /**
     * Constructor.
     * @param name Name of an animal.
     */
    public Animal(final String name)
    {
        this.name = name;
    }
    
    /**
     * hashCode() generated by Eclipse.
     */
    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        return result;
    }

    /**
     * equals() generated by Eclipse.
     */
    @Override
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Animal other = (Animal) obj;
        if (name == null)
        {
            if (other.name != null)
                return false;
        } else if (!name.equals(other.name))
            return false;
        return true;
    }

    /**
     * Make sound.
     */ 
    @Override
    public void makeSound()
    {
        System.out.println
            (String.format("%s says: %s", this.name, "beep"));
    }
    
    /**
     * Return name of the pet.
     */
    @Override
    public String getName()
    {
        return this.name;
    }
    
    /**
     * Update name of the pet.
     */
    @Override
    public void changeName(String newName)
    {
        this.name = newName;
    }
}